agents:
  queue: "macos-15"

steps:
  - group: ":hammer: Build Apps"
    steps:
      - label: ":android: Build Android App"
        key: "build_android_app"
        commands:
          - "./src/react-native-app/scripts/build.sh android"
          - "bundle exec upload-app --farm=bs --app=src/react-native-app/android/app/build/outputs/apk/release/app-release.apk --app-id-file=bs-android-url.txt"
        env:
          JAVA_VERSION: "17"
          NODE_VERSION: "22"
        plugins:
          artifacts#v1.5.0:
            upload:
              - "src/react-native-app/android/app/build/outputs/apk/release/app-release.apk"
              - "bs-android-url.txt"
        timeout_in_minutes: 20

      - label: ":ios: Build iOS App"
        key: "build_ios_app"
        agents:
          queue: "macos-14"
        commands:
          - "./src/react-native-app/scripts/build.sh ios"
          - "bundle exec upload-app --farm=bs --app=src/react-native-app/ios/output/reactnativeapp.ipa --app-id-file=bs-ios-url.txt"
        env:
          JAVA_VERSION: "17"
          NODE_VERSION: "18"
          XCODE_VERSION: "15.4.0"
        plugins:
          artifacts#v1.5.0:
            upload:
              - "src/react-native-app/ios/output/reactnativeapp.ipa"
              - "bs-ios-url.txt"
        timeout_in_minutes: 20
